### ISSUE TITLE
How to deploy it with a pure python environment?

### ISSUE THREAD

**Issue by ideactltd** [RenaudLN/dash_socketio#5]
This is an amazing project!
I only have one question. How can I deploy it to a pure python environment if npm steps are involved? I am not familiar with dash component development. Is it possible to pack everything into the python package and I simply install your package with pip install?

**Comment by RenaudLN** [comment]
Hey @ideactltd you don't need to do anything with npm to use it in your Dash app. Just pip install it and you're good to use it in your app. You can check my dash-firestore-chat repo for a full example of dash-socketio in action.
